### ISSUE TITLE
Зависимости sdk. Обновить okhttp, заменить picasso на glide

### ISSUE THREAD

**Issue by Sash0k** [iqstore/iqchannels-android#2]
- **okhttp** предлагаю актуализировать до версии [3.12.х](https://square.github.io/okhttp/changelog_3x/#version-3130).
И в дальнейшем до более новых, если будет поднята minSdkVersion библиотеки

- **picasso** предлагаю заменить на **glide**.
[Есть информация](https://proandroiddev.com/coil-vs-picasso-vs-glide-get-ready-go-774add8cfd40), что он лучше по производительности

**Comment by ivankorobkov** [comment]
Привет, да, спасибо. Как-нибудь займусь этим.
